# Site
repository: dreamow99/my-online-cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Duy Pham
title: Game Developer
email: duyphd9@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  dreamow99
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: duyphm
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
##  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    Software Engineer with a strong foundation in mobile game development using Unity. Eager to leverage my problem-solving skills and adaptability to contribute to innovative projects in a creative and challenging environment.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Unbound Labs
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Game Developer
        caption: May 2021 - Present
        description: | # this will include new lines to allow paragraphs
            Skill learned: Unity, Git

            Leverage Unity game engine to develop and maintain multiple casual mobile games for mobile platforms.

      - layout: left
        title: VNG Corporation
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Game Developer Freshser
        caption: May 2020 - Dec 2020
        description: | # this will include new lines to allow paragraphs
            Skill learned: JavaScript, Git

            Completed a project developing the client-side of a simple mobile game within a 3-person team.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Red Bounce Ball Adventure
        # link_text: Project link
        #additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          [Demo](https://play.google.com/store/apps/details?id=com.ball.adventure.color.red)
        description: | # this will include new lines to allow paragraphs
          My first project using Unity, this casual adventure game provided a foundation in core game development concepts and the Unity workflow.

      - layout: top-middle
        title: Merge Spider Train
        quote: >
          [Demo](https://play.google.com/store/apps/details?id=merge.choo.choo.horror.train)
        description: | # this will include new lines to allow paragraphs
          Developed the core game logic, including character controlling, character merging and enemy combat mechanics. Additionally, maintained and updated the game's SDK, ensuring smooth integration of third-party functionalities.

      - layout: top-middle
        title: Alphabet Merge - Maze Puzzle 2D
        quote: >
          [Demo](https://www.youtube.com/watch?v=IBrxJ3-wZP0/)
        description: | # this will include new lines to allow paragraphs
          Developed the core game logic, maintained and updated the game's SDK.

      - layout: top-middle
        title: Monster Maker - Mix & Fight
        quote: >
          [Demo](https://www.youtube.com/watch?v=FRjH8yliX9Q/)
        description: | # this will include new lines to allow paragraphs
          Implemented various mini-games within this monster creation and combat title, adding depth to the gameplay experience.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Engineering and Technology - Vietnam National University
        caption: 2017 - 2021
        sub_title: Bachelor of Computer Science
        quote: >
          Established in 2004 from the Faculty of Technology, it has grown over the years into one of the top universities in Vietnam for Information Technology and Engineering majors.
        description: | # this will include new lines to allow paragraphs
          Honed problem-solving skills and gained a strong foundation in Object-Oriented Programming (OOP), data structures, and algorithms during my time at UET, equipping me to tackle software development challenges effectively.

      - layout: left
        title: Hung Yen High School for the Gifted
        caption: 2014 - 2017
        sub_title: Mathematics

  - title: Licenses & certifications
    layout: list
    content:
      - layout: left
        title: TOEIC 895
        caption: IIG Vietnam
        sub_title: Issued Jan 2020 - Expired Jan 2022

  - title: Honors & awards
    layout: list
    content:
      - layout: left
        title: Consolation Prize in Vietnam Olympiad in Informatics
        caption: Issued by Vietnam Ministry of Education and Training · Dec 2015
        sub_title: Associated with Hung Yen High School for the Gifted

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
